name: flutter_interview
description: "A Flutter application to explore European countries with wishlist functionality."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

  # HTTP & Caching
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5

  # State Management
  flutter_bloc: ^8.1.6

  # Local Database
  drift: ^2.25.1
  sqlite3_flutter_libs: ^0.5.39
  sqlite3: ^2.9.4
  path_provider: ^2.1.5
  path: ^1.9.0

  # UI & Utils
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  get_it: ^8.2.0
  dartz: ^0.10.1

  # Code Generation
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Testing
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  drift_dev: ^2.25.1

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
